#!/bin/sh

_name=${1}
shift;

#set -ex
set -e

if [ -z "${_name}" ]; then
    echo "you must pass the name of the container to run"
    exit 1
fi

CMD=$(command -v podman || which docker)

$CMD exec -it ${_name} "$@"
