#!/bin/sh

_path=${1}
_what=${2}

#set -ex
#set -e
if [ -z "${_path}" ]; then
    echo "you must pass the path where to run the container"
    exit 1
fi

if [ -z "${_what}" ]; then
    echo "you must pass the container image to run"
    exit 1
fi

_storage=$(realpath ${_path})
if [ ! -d ${_storage} ]; then
    echo "Storage path is not accessible ${_storage}"
    exit 1
fi

_env_file=$(find ${_storage} -iname ".env*" | tail -n1)
if [ ! -f ${_env_file} ]; then
    echo "env file is not accessible in path ${_storage}"
    exit 1
fi
_name=$(grep HOSTNAME ${_env_file} | tail -n1 | cut -d'=' -f 2 | cut -d':' -f 2)
_port=$(grep LISTEN ${_env_file} | tail -n1 | cut -d'=' -f 2 | cut -d':' -f 2)
_env=$(grep ENV ${_env_file} | tail -n1 | cut -d'=' -f 2 | cut -d':' -f 2)

echo ${_env}

CMD=$(command -v podman || which docker)

$CMD run --pull=newer --network=host --name=${_name} --replace -v ${_env_file}:/.env -v ${_storage}:/storage --env-file=${_env_file} ${_what} fedbox -env ${_env}
